server:
  port: 8083

spring:
  application:
    name: GestionAcademica

  datasource:
    url: jdbc:postgresql://localhost:6435/db_academica
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true