server:
  port: 8083

spring:
  application:
    name: GestionAcademica

  datasource:
    url: jdbc:mysql://localhost:3306/academic_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true